In [6]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
import matplotlib.pyplot as plt

In [9]:
%matplotlib inline

In [11]:
data = pd.read_csv("D:\MachineLearning\A-Z Machine Learning\P14-Part3-Classification\Section 22 - Random Forest Classification\Python\Social_Network_Ads.csv")
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [12]:
data = data.drop("User ID", axis=1)

In [13]:
x = data.iloc[:, :-1]
x

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [14]:
y = data.iloc[:, -1]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [15]:
dummy_gender = pd.get_dummies(data["Gender"], drop_first=True)
dummy_gender

Male
0       1
1       1
2       0
3       0
4       1
..    ...
395     0
396     1
397     0
398     1
399     0

[400 rows x 1 columns]

In [17]:
x = x.drop("Gender", axis=1)
x

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [18]:
x = pd.concat([x, dummy_gender], axis=1)
x

Age  EstimatedSalary  Male
0     19            19000     1
1     35            20000     1
2     26            43000     0
3     27            57000     0
4     19            76000     1
..   ...              ...   ...
395   46            41000     0
396   51            23000     1
397   50            20000     0
398   36            33000     1
399   49            36000     0

[400 rows x 3 columns]

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()

In [22]:
x.iloc[:, :-1] = sc.fit_transform(x.iloc[:, :-1])

In [23]:
x

Age  EstimatedSalary  Male
0   -1.781797        -1.490046     1
1   -0.253587        -1.460681     1
2   -1.113206        -0.785290     0
3   -1.017692        -0.374182     0
4   -1.781797         0.183751     1
..        ...              ...   ...
395  0.797057        -0.844019     0
396  1.274623        -1.372587     1
397  1.179110        -1.460681     0
398 -0.158074        -1.078938     1
399  1.083596        -0.990844     0

[400 rows x 3 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)

In [30]:
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [31]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix, classification_report

In [35]:
confusion_matrix(y_test, y_pred)

array([[54,  4],
       [ 2, 20]], dtype=int64)

In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.93      0.95        58
           1       0.83      0.91      0.87        22

    accuracy                           0.93        80
   macro avg       0.90      0.92      0.91        80
weighted avg       0.93      0.93      0.93        80



In [37]:
from sklearn.model_selection import RandomizedSearchCV

In [41]:
parameters = [{'n_estimators' : [100, 200, 300, 400, 500], 
               "criterion" : ['gini', 'entropy'],
               'max_depth' : [3, 5, 10, None],
               'max_features' : ['auto', 'sqrt', 'log2'],
               'bootstrap' : [True, False]}]

In [42]:
parameters

[{'n_estimators': [100, 200, 300, 400, 500],
  'criterion': ['gini', 'entropy'],
  'max_depth': [3, 5, 10, None],
  'max_features': ['auto', 'sqrt', 'log2'],
  'bootstrap': [True, False]}]

In [43]:
rand_search = RandomizedSearchCV(estimator= classifier, param_distributions= parameters, scoring= 'accuracy', cv=10, n_jobs=-1)

In [55]:
rand_search = rand_search.fit(x_train, y_train)

In [56]:
best_accuracy = rand_search.best_score_

In [57]:
best_accuracy

0.9

In [58]:
best_params = rand_search.best_params_

In [59]:
best_params

{'n_estimators': 300,
 'max_features': 'auto',
 'max_depth': 5,
 'criterion': 'gini',
 'bootstrap': False}

In [60]:
new_classifier = RandomForestClassifier(n_estimators= 300, criterion = 'gini', max_features = 'auto', max_depth =  5, bootstrap = False)

In [61]:
new_classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [62]:
new_y_pred = new_classifier.predict(x_test)
new_y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [64]:
confusion_matrix(y_test, new_y_pred)

array([[55,  3],
       [ 1, 21]], dtype=int64)

In [65]:
print(classification_report(y_test, new_y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

